/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.hesge.sedypro.utils;

/**
 * Represents a single trace entry generated by an code instrumentor.
 * 
 * Copyright HEG Geneva 2014, Switzerland
 * 
 * @author Eric Harth
 */

public class Trace {

	// Private attributes
	private int		keyId;
	private int     level;
	private String	instanceId;
	private String	packagename;
	private String	classname;
	private long	    threadId;
	private String	signature;
	private boolean	isEnteringTrace;
	private String	returnType;
	private long	    timestamp;
	private String  arguments;
	private long	    duration;

	/**
	 * Default constructor
	 */
	public Trace() {
	}

	public int getKeyId() {
		return keyId;
	}

	public void setKeyId(int keyId) {
		this.keyId = keyId;
	}

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getInstanceId() {
		return instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	public String getPackageName() {
		return packagename;
	}

	public void setPackageName(String packagename) {
		this.packagename = packagename;
	}

	public String getClassName() {
		return classname;
	}

	public void setClassName(String classname) {
		this.classname = classname;
	}

	public long getThreadId() {
		return threadId;
	}

	public void setThreadId(long threadId) {
		this.threadId = threadId;
	}

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public boolean isEnteringTrace() {
		return isEnteringTrace;
	}

	public void setEnteringTrace(boolean isEnteringTrace) {
		this.isEnteringTrace = isEnteringTrace;
	}

	public String getReturnType() {
		return returnType;
	}

	public void setReturnType(String returnType) {
		this.returnType = returnType;
	}

	public long getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}

	public long getDuration() {
		return duration;
	}

	public void setDuration(long duration) {
		this.duration = duration;
	}

	public String getArguments() {
		return arguments;
	}

	public void setArguments(String arguments) {
		this.arguments = arguments;
	}

}
