/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.hesge.sedypro.utils;

import java.util.ArrayList;
import java.util.List;

import edu.mit.jwi.item.POS;

/**
 * Represents a single trace entry generated by an code instrumentor.
 * 
 * Copyright HEG Geneva 2014, Switzerland
 * 
 * @author Eric Harth
 */

public class Word {

	// Private attributes
	private POS pos;
	private String lemma;
	private List<Concept> senses;

	/**
	 * Default constructor
	 */
	public Word() {
		senses = new ArrayList<>();
	}

	public String getLemma() {
		return lemma;
	}

	public void setLemma(String lemma) {
		this.lemma = lemma;
	}

	public POS getPos() {
		return pos;
	}

	public void setPos(POS pos) {
		this.pos = pos;
	}

	public List<Concept> getSenses() {
		return senses;
	}
}
